#!/usr/bin/with-contenv bash

set -u # Unset Variables are an error
set -e # Exit on error

# Ensure Data folder Exists
DATA_PATH='/data/ToonamiAftermath'
if [ ! -d $DATA_PATH ]; then
	echo "First boot with mounted /data/ToonamiAftermath detected."
	mkdir -p $DATA_PATH
fi